test rds

diff --git a/.github/workflows/deploy-changed-cf.yaml b/.github/workflows/deploy-changed-cf.yaml
--- a/.github/workflows/deploy-changed-cf.yaml
+++ b/.github/workflows/deploy-changed-cf.yaml
@@ -1,11 +1,11 @@
 name: Deploy changed CloudFormation templates
 on:
-  push:
-    branches:
-      - master
-    paths:
-      - 'cf/**.yaml'
-      - 'cf/**.yml'
+  # push:
+  #   branches:
+  #     - master
+  #   paths:
+  #     - 'cf/**.yaml'
+  #     - 'cf/**.yml'
   pull_request:
     branches:
       - master
@@ -34,18 +34,14 @@ jobs:
         run: |-
           # Merge all modified and renamed files into one JSON array
           #jq -s add ${HOME}/files_added.json ${HOME}/files_modified.json ${HOME}/files_renamed.json > ${HOME}/files_to_check.json
-
           cat ${HOME}/files.json
           echo
-
           # Select those that are CF templates (path starts with `cf/`)
           jq '[.[] | select(match("^cf/"))]' ${HOME}/files.json > ${HOME}/cf_files.json
-
           # Set as output the minified JSON.
           echo "::set-output name=files::$(jq -c . < ${HOME}/cf_files.json)"
           echo "$(jq -c . < ${HOME}/cf_files.json)"
           echo "::set-output name=num-files::$(jq '. | length' ${HOME}/cf_files.json)"
-
   deploy-templates:
     name: Deploy changed CloudFormation template
     runs-on: ubuntu-20.04
@@ -53,7 +49,7 @@ jobs:
     if: needs.get-modified-templates.outputs.num-files > 0
     strategy:
       matrix:
-        environment: ['production', 'staging']
+        environment: ['staging']
         template: ${{fromJson(needs.get-modified-templates.outputs.files)}}
     env:
       CLUSTER_ENV: ${{ matrix.environment }}
@@ -62,11 +58,11 @@ jobs:
         name: Check out source code
         uses: actions/checkout@v2
 
-      - id: lint
-        name: Lint template
-        uses: scottbrenner/cfn-lint-action@1.6.1
-        with:
-          args: ${{ matrix.template }}
+      # - id: lint
+      #   name: Lint template
+      #   uses: scottbrenner/cfn-lint-action@1.6.1
+      #   with:
+      #     args: ${{ matrix.template }}
 
       - id: set-up-creds
         name: Configure AWS credentials
@@ -77,26 +73,39 @@ jobs:
           aws-region: ${{ env.region }}
 
       # This is only necessary for IAM Service Account roles.
-      - id: get-oidc
-        if: ${{ contains(matrix.template, 'irsa-') && github.ref == 'refs/heads/master' }}
-        name: Get OIDC provider information for IRSA role
-        run: |-
-          OIDC_PROVIDER=$(aws eks describe-cluster --name "biomage-$CLUSTER_ENV" --query "cluster.identity.oidc.issuer" --output text | sed -e "s/^https:\/\///")
-          echo "::set-output name=oidc-provider::$OIDC_PROVIDER"
+      # - id: get-oidc
+      #   if: ${{ contains(matrix.template, 'irsa-') && github.ref == 'refs/heads/master' }}
+      #   name: Get OIDC provider information for IRSA role
+      #   run: |-
+      #     OIDC_PROVIDER=$(aws eks describe-cluster --name "biomage-$CLUSTER_ENV" --query "cluster.identity.oidc.issuer" --output text | sed -e "s/^https:\/\///")
+      #     echo "::set-output name=oidc-provider::$OIDC_PROVIDER"
 
       - id: set-name
         name: Set name of the CloudFormation stack
         run: |-
           echo "Ref is $GITHUB_REF"
-          BASE_NAME=biomage-$(basename $FILE_NAME | sed "s/\..*//")-$CLUSTER_ENV
-          echo "::set-output name=stack-name::$BASE_NAME"
+          BASE_NAME=$(basename $FILE_NAME | sed "s/\..*//")
+          STACK_NAME=biomage-$BASE_NAME-$CLUSTER_ENV
+          echo "::set-output name=file-name::$BASE_NAME"
+          echo "::set-output name=stack-name::$STACK_NAME"
         env:
           FILE_NAME: ${{ matrix.template }}
 
+      # - id: deploy-irsa-template
+      #   if: ${{ contains(matrix.template, 'irsa-') && github.ref == 'refs/heads/master' }}
+      #   name: Deploy IRSA CloudFormation template
+      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
+      #   with:
+      #     parameter-overrides: "Environment=${{ matrix.environment }},OIDCProvider=${{ steps.get-oidc.outputs.oidc-provider }}"
+      #     name: ${{ steps.set-name.outputs.stack-name }}
+      #     template: ${{ matrix.template }}
+      #     no-fail-on-empty-changeset: "1"
+      #     capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
+
       - id: deploy-template
-        name: Deploy CloudFormation template
-        if: ${{ !contains(matrix.template, 'irsa-') && github.ref == 'refs/heads/master' }}
+        if: ${{ !contains(matrix.template, 'irsa-') }}
         uses: aws-actions/aws-cloudformation-github-deploy@v1
+        name: Deploy CloudFormation template
         with:
           parameter-overrides: "Environment=${{ matrix.environment }}"
           name: ${{ steps.set-name.outputs.stack-name }}
@@ -104,13 +113,97 @@ jobs:
           no-fail-on-empty-changeset: "1"
           capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
 
-      - id: deploy-irsa-template
-        if: ${{ contains(matrix.template, 'irsa-') && github.ref == 'refs/heads/master' }}
-        name: Deploy IRSA CloudFormation template
-        uses: aws-actions/aws-cloudformation-github-deploy@v1
+        # There is no easy way in CF to create dependencies between stacks
+        # Meanwhile we need the RDS agent to up before we can set up the database roles
+        # This step checks for the RDS agent to be up before we proceed. It retries if the rds agent is not up.
+      - id: wait-for-stack
+        name: Wait for CF stack to complete before continuing
+        if: ${{ steps.set-name.outputs.file-name == 'test-rds' }}
+        uses: nick-invision/retry@v2
         with:
-          parameter-overrides: "Environment=${{ matrix.environment }},OIDCProvider=${{ steps.get-oidc.outputs.oidc-provider }}"
-          name: ${{ steps.set-name.outputs.stack-name }}
-          template: ${{ matrix.template }}
-          no-fail-on-empty-changeset: "1"
-          capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
+          timeout_seconds: 600
+          max_attempts: 20
+          retry_on: error
+          on_retry_command: sleep $(shuf -i 5-15 -n 1)
+          command: |-
+            AGENT_STACK_NAME="biomage-test-rds-agent-${CLUSTER_ENV}"
+            STACK_STATUS=$(aws cloudformation describe-stacks --stack-name $AGENT_STACK_NAME | jq -c '.Stacks[0].StackStatus' | tr -d '"')
+            if [ "$STACK_STATUS" != "CREATE_COMPLETE" ] && [ "$STACK_STATUS" != "UPDATE_COMPLETE" ]; then
+                echo "Stack is not up, retrying..."
+                exit 1
+            fi
+      # This step is needed to change the environment name (e.g. staging) into its uppercase form.
+      # This is required because the action that is used in get-rds-secrets store the secret in environment variables,
+      # with uppercase letters (see action ref). Therefore, we need the uppercased form of the environment
+      # Which is output in .outputs.uppercase of this step.
+      - id: setup-rds-env
+        if: ${{ steps.set-name.outputs.file-name == 'test-rds' }}
+        name: Uppercase environment name
+        uses: ASzc/change-string-case-action@v2
+        with:
+          string: ${{ matrix.environment }}
+
+      - id: get-rds-secrets
+        if: ${{ steps.set-name.outputs.file-name == 'test-rds' }}
+        name: Export RDS secrets into environment variables
+        uses: abhilash1in/aws-secrets-manager-action@v2.0.0
+        with:
+          secrets: aurora-${{ matrix.environment }}
+          parse-json: true
+
+      - id: check-rds-secrets
+        if: ${{ steps.set-name.outputs.file-name == 'test-rds'}}
+        name: Check RDS secrets are fetched
+        run: |-
+          # These checks if the RDS username and passwords are set
+          if [ -z $AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME ]; then
+            echo "RDS username not provided"
+            exit 1
+          fi
+          if [ -z $AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_PASSWORD ]; then
+            echo "RDS password not provided"
+            exit 1
+          fi
+      - id: setup-rds-roles
+        if: ${{ steps.set-name.outputs.file-name == 'test-rds'}}
+        name: Setup RDS roles for default RDS instances
+        run: |-
+          INSTANCE_ID=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=rds-${CLUSTER_ENV}-ssm-agent" \
+            --output text \
+            --query 'Reservations[*].Instances[*].InstanceId')
+          if [ -z $INSTANCE_ID ]; then
+            echo "Can not connect to RDS agent: No instances found for $CLUSTER_ENV"
+            exit 1
+          fi
+          CLUSTER_NAME=aurora-cluster-${CLUSTER_ENV}-default
+          RDSHOST=$(aws rds describe-db-cluster-endpoints \
+            --region $REGION \
+            --db-cluster-identifier $CLUSTER_NAME \
+            --filter Name=db-cluster-endpoint-type,Values='writer' \
+            --query 'DBClusterEndpoints[0].Endpoint' \
+            --output text)
+          if [ -z $RDSHOST ]; then
+            echo "Failed getting RDS host with name $CLUSTER_NAME"
+            exit 1
+          fi
+          SETUP_ROLES_CMD="
+            PGPASSWORD=${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_PASSWORD} psql \
+              --host=${RDSHOST} \
+              --port=5432 \
+              --username=${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME} \
+              --dbname=aurora_db <<EOF
+                CREATE ROLE api_role WITH LOGIN;
+                CREATE ROLE dev_role WITH LOGIN;
+                GRANT USAGE ON SCHEMA public TO api_role;
+                GRANT dev_role TO ${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME};
+                ALTER DEFAULT PRIVILEGES FOR USER dev_role IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_role;
+                REVOKE dev_role FROM ${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME};
+                GRANT rds_iam TO api_role;
+                GRANT rds_iam, ${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME} TO dev_role;
+              EOF"
+          aws ssm send-command --instance-ids "$INSTANCE_ID" \
+            --document-name AWS-RunShellScript \
+            --parameters "commands='$SETUP_ROLES_CMD'"
+        env:
+          REGION: ${{ env.region }}
