add wait and retry step

diff --git a/.github/workflows/deploy-changed-cf.yaml b/.github/workflows/deploy-changed-cf.yaml
--- a/.github/workflows/deploy-changed-cf.yaml
+++ b/.github/workflows/deploy-changed-cf.yaml
@@ -118,7 +118,31 @@ jobs:
           no-fail-on-empty-changeset: "1"
           capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
 
-      - id: env
+        # There is no easy way in CF to create dependencies between stacks
+        # Meanwhile we need the RDS agent to up before we can set up the database roles
+        # This step checks for the RDS agent to be up before we proceed. It retries if the rds agent is not up.
+      - id: wait-for-stack
+        name: Wait for CF stack to complete before continuing
+        if: ${{ steps.set-name.outputs.file-name == 'rds' && github.ref == 'refs/heads/master' }}
+        uses: nick-invision/retry@v2
+        with:
+          timeout_seconds: 600
+          max_attempts: 20
+          retry_on: error
+          on_retry_command: sleep $(shuf -i 5-15 -n 1)
+          command: |-
+            AGENT_STACK_NAME="biomage-rds-agent-${CLUSTER_ENV}"
+            STACK_STATUS=$(aws cloudformation describe-stacks --stack-name $AGENT_STACK_NAME | jq -c '.Stacks[0].StackStatus' | tr -d '"')
+            if [ "$STACK_STATUS" != "CREATE_COMPLETE" ] && [ "$STACK_STATUS" != "UPDATE_COMPLETE" ]; then
+                echo "Stack is not up, retrying..."
+                exit 1
+            fi
+
+      # This step is needed to change the environment name (e.g. staging) into its uppercase form.
+      # This is required because the action that is used in get-rds-secrets store the secret in environment variables,
+      # with uppercase letters (see action ref). Therefore, we need the uppercased form of the environment
+      # Which is output in .outputs.uppercase of this step.
+      - id: setup-rds-env
         if: ${{ steps.set-name.outputs.file-name == 'rds' && github.ref == 'refs/heads/master' }}
         name: Uppercase environment name
         uses: ASzc/change-string-case-action@v2
@@ -138,11 +162,11 @@ jobs:
         name: Check RDS secrets are fetched
         run: |-
           # These checks if the RDS username and passwords are set
-          if [ -z $AURORA_${{ steps.env.outputs.uppercase }}_USERNAME ]; then
+          if [ -z $AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME ]; then
             echo "RDS username not provided"
             exit 1
           fi
-          if [ -z $AURORA_${{ steps.env.outputs.uppercase }}_PASSWORD ]; then
+          if [ -z $AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_PASSWORD ]; then
             echo "RDS password not provided"
             exit 1
           fi
@@ -171,19 +195,19 @@ jobs:
             exit 1
           fi
           SETUP_ROLES_CMD="
-            PGPASSWORD=${AURORA_${{ steps.env.outputs.uppercase }}_PASSWORD} psql \
+            PGPASSWORD=${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_PASSWORD} psql \
               --host=${RDSHOST} \
               --port=5432 \
-              --username=${AURORA_${{ steps.env.outputs.uppercase }}_USERNAME} \
+              --username=${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME} \
               --dbname=aurora_db <<EOF
                 CREATE ROLE api_role WITH LOGIN;
                 CREATE ROLE dev_role WITH LOGIN;
                 GRANT USAGE ON SCHEMA public TO api_role;
-                GRANT dev_role TO ${AURORA_${{ steps.env.outputs.uppercase }}_USERNAME};
+                GRANT dev_role TO ${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME};
                 ALTER DEFAULT PRIVILEGES FOR USER dev_role IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_role;
-                REVOKE dev_role FROM ${AURORA_${{ steps.env.outputs.uppercase }}_USERNAME};
+                REVOKE dev_role FROM ${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME};
                 GRANT rds_iam TO api_role;
-                GRANT rds_iam, ${AURORA_${{ steps.env.outputs.uppercase }}_USERNAME} TO dev_role;
+                GRANT rds_iam, ${AURORA_${{ steps.setup-rds-env.outputs.uppercase }}_USERNAME} TO dev_role;
               EOF"
           aws ssm send-command --instance-ids "$INSTANCE_ID" \
             --document-name AWS-RunShellScript \
